import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

interface PrivacySection { title: string; paragraphs: string[]; }

@Component({
  selector: 'app-privacy',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './privacy.html',
  styleUrl: './privacy.css'
})
export class Privacy {
  readonly sections: PrivacySection[] = [
    { title: '1. OBJETIVO', paragraphs: ['A [RAZÃO SOCIAL], responsável pelo aplicativo Bora Trampa, valoriza a privacidade e a proteção dos dados pessoais. Esta Política explica como os dados são coletados, utilizados, armazenados, compartilhados e protegidos, em conformidade com a Lei nº 13.709/2018 — LGPD e demais normas aplicáveis.'] },
    { title: '2. SOBRE O BORA TRAMPA', paragraphs: ['O Bora Trampa é uma plataforma digital de intermediação de serviços que conecta clientes e profissionais, permitindo solicitação e contratação de serviços, pagamento dentro do aplicativo, intermediação da operação e repasse de valores ao profissional, conforme as regras da plataforma.'] },
    { title: '3. CONTROLADORA', paragraphs: ['Razão social: [RAZÃO SOCIAL]\nCNPJ: [CNPJ]\nEndereço: [ENDEREÇO]\nE-mail: [E-MAIL]\nEncarregado/DPO: [NOME/E-MAIL]'] },
    { title: '4. DADOS DE CLIENTES', paragraphs: ['Podem ser coletados, conforme o uso: nome, CPF, data de nascimento, telefone, e-mail, senha ou dados de autenticação, foto, localização, endereço e informações necessárias para contratação e pagamento.'] },
    { title: '5. DADOS DE PROFISSIONAIS', paragraphs: ['Podem ser coletados: nome, CPF, data de nascimento, telefone, e-mail, foto, categoria profissional, serviços oferecidos, valores, região de atendimento, disponibilidade, experiência e dados necessários para recebimento.'] },
    { title: '6. VERIFICAÇÃO DE IDENTIDADE DOS PROFISSIONAIS', paragraphs: ['Para aumentar a segurança da plataforma, os profissionais poderão ser submetidos a verificação de identidade. Poderão ser solicitados RG ou outro documento oficial, selfie, selfie segurando o documento, comprovante de endereço, CPF e outras informações necessárias à validação.', 'Esses dados serão utilizados para identificação, validação cadastral, segurança, prevenção de fraude, prevenção de contas falsas, proteção de clientes e profissionais e cumprimento de obrigações legais, quando aplicável.', 'Os documentos enviados para verificação não serão exibidos no perfil público do profissional nem disponibilizados aos clientes.', 'Quando a verificação envolver tratamento de características biométricas, o tratamento deverá observar as regras aplicáveis aos dados pessoais sensíveis previstas na LGPD.'] },
    { title: '7. LOCALIZAÇÃO', paragraphs: ['Quando autorizado, o Bora Trampa poderá utilizar localização para encontrar profissionais próximos, identificar região de atendimento, facilitar contratações, melhorar a experiência e auxiliar na segurança. O usuário poderá controlar essa permissão nas configurações do dispositivo.'] },
    { title: '8. PAGAMENTOS E REPASSES', paragraphs: ['Para permitir contratação e pagamento dentro do aplicativo, poderão ser tratados dados necessários para processamento da transação, confirmação da contratação, cobrança da taxa de intermediação, reembolsos, prevenção de fraude, conciliação e repasse ao profissional.', 'O Bora Trampa poderá utilizar instituições financeiras, instituições de pagamento, gateways, adquirentes e outros parceiros especializados.'] },
    { title: '9. TAXA DE INTERMEDIAÇÃO', paragraphs: ['O Bora Trampa poderá cobrar do cliente uma taxa de intermediação informada antes da confirmação da contratação. A política de privacidade trata dos dados necessários para viabilizar essa cobrança; os valores e regras comerciais serão detalhados nos Termos de Uso.'] },
    { title: '10. HISTÓRICO DE CONTRATAÇÕES', paragraphs: ['Poderão ser armazenadas informações sobre serviço, cliente, profissional, valor, taxa, data, horário, status, pagamento, repasse, cancelamentos, reembolsos, avaliações e solicitações de suporte, quando necessário para funcionamento, segurança, atendimento, prevenção de fraude, obrigações legais e exercício regular de direitos.'] },
    { title: '11. FINALIDADES DO TRATAMENTO', paragraphs: ['Os dados poderão ser utilizados para criar e administrar contas; verificar identidade; conectar clientes e profissionais; permitir contratações; processar pagamentos e repasses; enviar notificações; permitir avaliações; prevenir fraudes; melhorar a plataforma; prestar atendimento; cumprir obrigações legais; exercer direitos; e realizar comunicações promocionais quando permitidas.'] },
    { title: '12. BASES LEGAIS', paragraphs: ['O tratamento poderá ocorrer, conforme a finalidade, com base nas hipóteses previstas na LGPD, incluindo execução de contrato ou procedimentos preliminares, cumprimento de obrigação legal ou regulatória, exercício regular de direitos, prevenção à fraude e segurança, legítimo interesse quando aplicável e consentimento quando necessário.'] },
    { title: '13. COMPARTILHAMENTO', paragraphs: ['Os dados poderão ser compartilhados, quando necessário, com provedores de tecnologia e hospedagem, serviços de verificação de identidade, parceiros de pagamento, instituições financeiras, serviços antifraude, atendimento, consultorias e autoridades públicas quando houver obrigação legal. O compartilhamento será limitado ao necessário para as finalidades aplicáveis.'] },
    { title: '14. DADOS VISÍVEIS ENTRE USUÁRIOS', paragraphs: ['Para viabilizar o serviço, determinadas informações poderão ser disponibilizadas entre cliente e profissional, como nome, foto, informações profissionais, serviço, região e, quando necessário, informações do local do atendimento.', 'RG, selfie de verificação, selfie com documento, comprovante de endereço e dados bancários não serão disponibilizados publicamente.'] },
    { title: '15. COOKIES E TECNOLOGIAS', paragraphs: ['O aplicativo poderá utilizar cookies, SDKs, identificadores e tecnologias semelhantes para funcionamento, segurança, estatísticas, análise de uso, melhoria da experiência e marketing, quando aplicável.'] },
    { title: '16. SEGURANÇA', paragraphs: ['O Bora Trampa adotará medidas técnicas e administrativas compatíveis com os riscos para proteger os dados contra acessos não autorizados, perda, alteração, destruição, divulgação ou uso indevido. Nenhum sistema é completamente seguro.'] },
    { title: '17. INCIDENTES', paragraphs: ['Em caso de incidente de segurança envolvendo dados pessoais, o Bora Trampa adotará medidas de contenção, investigação e mitigação e realizará as comunicações exigidas pela legislação, quando aplicável.'] },
    { title: '18. ARMAZENAMENTO E TRANSFERÊNCIA INTERNACIONAL', paragraphs: ['Os dados poderão ser armazenados no Brasil ou no exterior por fornecedores de infraestrutura. Quando houver transferência internacional, serão observados os requisitos da LGPD e as regulamentações aplicáveis.'] },
    { title: '19. PRAZO DE RETENÇÃO', paragraphs: ['Os dados serão mantidos pelo período necessário às finalidades do tratamento. Após o encerramento da conta, determinados dados poderão ser mantidos para cumprimento de obrigações legais, prevenção de fraude, segurança, exercício regular de direitos, obrigações fiscais ou outras hipóteses permitidas pela legislação.'] },
    { title: '20. DIREITOS DOS TITULARES', paragraphs: ['O usuário poderá exercer os direitos previstos na LGPD, conforme aplicável, incluindo confirmação e acesso, correção, anonimização, bloqueio ou eliminação quando cabível, informações sobre compartilhamento, portabilidade quando aplicável, revogação de consentimento, oposição a determinados tratamentos e demais direitos previstos em lei.'] },
    { title: '21. CANAL DE PRIVACIDADE', paragraphs: ['Solicitações poderão ser encaminhadas para: [E-MAIL DE PRIVACIDADE]. Encarregado/DPO: [NOME/E-MAIL]. Poderão ser solicitadas informações adicionais para confirmação da identidade do titular.'] },
    { title: '22. EXCLUSÃO DA CONTA', paragraphs: ['O usuário poderá solicitar a exclusão da conta pelos meios disponibilizados. A exclusão não implica necessariamente eliminação imediata de informações que devam ser mantidas por obrigação legal, prevenção de fraude, segurança, exercício regular de direitos ou outra hipótese legal.'] },
    { title: '23. MENORES DE IDADE', paragraphs: ['O Bora Trampa deverá definir nos Termos de Uso a idade mínima para utilização. Quando houver tratamento de dados de crianças ou adolescentes, deverão ser observadas as exigências específicas da legislação e o melhor interesse desses titulares.'] },
    { title: '24. ALTERAÇÕES', paragraphs: ['Esta Política poderá ser atualizada para refletir mudanças no aplicativo, legislação, tecnologia ou operações. Alterações relevantes poderão ser comunicadas pelos canais disponíveis.'] },
    { title: '25. CONTATO', paragraphs: ['Bora Trampa\nRazão social: [RAZÃO SOCIAL]\nCNPJ: [CNPJ]\nE-mail: [E-MAIL]\nEndereço: [ENDEREÇO]\nEncarregado/DPO: [NOME/E-MAIL]'] }
  ];
}
