import Link from 'next/link';

const sections: [string,string][] = [
['1. OBJETIVO','A [RAZÃO SOCIAL], responsável pelo aplicativo Bora Trampa, valoriza a privacidade e a proteção dos dados pessoais. Esta Política explica como os dados são coletados, utilizados, armazenados, compartilhados e protegidos, em conformidade com a Lei nº 13.709/2018 — LGPD e demais normas aplicáveis.'],
['2. SOBRE O BORA TRAMPA','O Bora Trampa é uma plataforma digital de intermediação de serviços que conecta clientes e profissionais, permitindo solicitação e contratação de serviços, pagamento dentro do aplicativo, intermediação da operação e repasse de valores ao profissional, conforme as regras da plataforma.'],
['3. CONTROLADORA','Razão social: [RAZÃO SOCIAL]\nCNPJ: [CNPJ]\nEndereço: [ENDEREÇO]\nE-mail: [E-MAIL]\nEncarregado/DPO: [NOME/E-MAIL]'],
['4. DADOS DE CLIENTES','Podem ser coletados, conforme o uso: nome, CPF, data de nascimento, telefone, e-mail, senha ou dados de autenticação, foto, localização, endereço e informações necessárias para contratação e pagamento.'],
['5. DADOS DE PROFISSIONAIS','Podem ser coletados: nome, CPF, data de nascimento, telefone, e-mail, foto, categoria profissional, serviços oferecidos, valores, região de atendimento, disponibilidade, experiência e dados necessários para recebimento.'],
['6. VERIFICAÇÃO DE IDENTIDADE DOS PROFISSIONAIS','Os profissionais poderão ser submetidos a verificação de identidade, com solicitação de RG ou documento oficial, selfie, selfie segurando o documento, comprovante de endereço, CPF e outras informações necessárias. Esses dados serão utilizados para identificação, validação cadastral, segurança, prevenção de fraude e contas falsas, proteção de clientes e profissionais e cumprimento de obrigações legais. Documentos enviados não serão exibidos no perfil público nem disponibilizados aos clientes. Dados biométricos observarão as regras aplicáveis aos dados sensíveis da LGPD.'],
['7. LOCALIZAÇÃO','Quando autorizado, o Bora Trampa poderá utilizar localização para encontrar profissionais próximos, identificar região de atendimento, facilitar contratações, melhorar a experiência e auxiliar na segurança. O usuário poderá controlar essa permissão no dispositivo.'],
['8. PAGAMENTOS E REPASSES','Poderão ser tratados dados necessários para processamento da transação, confirmação, cobrança da taxa de intermediação, reembolsos, prevenção de fraude, conciliação e repasse ao profissional. Poderão ser utilizados parceiros especializados.'],
['9. TAXA DE INTERMEDIAÇÃO','O Bora Trampa poderá cobrar do cliente uma taxa de intermediação informada antes da confirmação. Os valores e regras comerciais serão detalhados nos Termos de Uso.'],
['10. HISTÓRICO DE CONTRATAÇÕES','Poderão ser armazenadas informações sobre serviço, cliente, profissional, valor, taxa, data, horário, status, pagamento, repasse, cancelamentos, reembolsos, avaliações e solicitações de suporte quando necessário ao funcionamento, segurança, atendimento, prevenção de fraude, obrigações legais e exercício de direitos.'],
['11. FINALIDADES DO TRATAMENTO','Os dados poderão ser utilizados para criar e administrar contas; verificar identidade; conectar clientes e profissionais; permitir contratações; processar pagamentos e repasses; enviar notificações; permitir avaliações; prevenir fraudes; melhorar a plataforma; atender; cumprir obrigações legais; exercer direitos; e realizar comunicações promocionais quando permitidas.'],
['12. BASES LEGAIS','O tratamento poderá ocorrer com base nas hipóteses previstas na LGPD, incluindo execução de contrato, obrigação legal ou regulatória, exercício regular de direitos, prevenção à fraude e segurança, legítimo interesse quando aplicável e consentimento quando necessário.'],
['13. COMPARTILHAMENTO','Os dados poderão ser compartilhados, quando necessário, com provedores de tecnologia e hospedagem, serviços de verificação, parceiros de pagamento, instituições financeiras, serviços antifraude, atendimento, consultorias e autoridades públicas quando houver obrigação legal.'],
['14. DADOS VISÍVEIS ENTRE USUÁRIOS','Poderão ser disponibilizados entre cliente e profissional nome, foto, informações profissionais, serviço, região e, quando necessário, local do atendimento. RG, selfies de verificação, comprovante de endereço e dados bancários não serão disponibilizados publicamente.'],
['15. COOKIES E TECNOLOGIAS','O aplicativo poderá utilizar cookies, SDKs, identificadores e tecnologias semelhantes para funcionamento, segurança, estatísticas, análise de uso, melhoria da experiência e marketing, quando aplicável.'],
['16. SEGURANÇA','O Bora Trampa adotará medidas técnicas e administrativas compatíveis com os riscos para proteger dados contra acessos não autorizados, perda, alteração, destruição, divulgação ou uso indevido. Nenhum sistema é completamente seguro.'],
['17. INCIDENTES','Em caso de incidente de segurança envolvendo dados pessoais, serão adotadas medidas de contenção, investigação e mitigação, além das comunicações exigidas pela legislação quando aplicável.'],
['18. ARMAZENAMENTO E TRANSFERÊNCIA INTERNACIONAL','Os dados poderão ser armazenados no Brasil ou no exterior por fornecedores de infraestrutura. Em transferências internacionais, serão observados os requisitos da LGPD e regulamentações aplicáveis.'],
['19. PRAZO DE RETENÇÃO','Os dados serão mantidos pelo período necessário às finalidades. Após o encerramento da conta, determinados dados poderão ser mantidos para obrigações legais, prevenção de fraude, segurança, exercício de direitos, obrigações fiscais ou outras hipóteses legais.'],
['20. DIREITOS DOS TITULARES','O usuário poderá exercer direitos previstos na LGPD, incluindo confirmação e acesso, correção, anonimização, bloqueio ou eliminação quando cabível, informações sobre compartilhamento, portabilidade, revogação de consentimento, oposição e demais direitos previstos em lei.'],
['21. CANAL DE PRIVACIDADE','Solicitações poderão ser encaminhadas para: [E-MAIL DE PRIVACIDADE]. Encarregado/DPO: [NOME/E-MAIL]. Poderão ser solicitadas informações para confirmação da identidade.'],
['22. EXCLUSÃO DA CONTA','O usuário poderá solicitar a exclusão da conta. Isso não implica necessariamente eliminação imediata de informações que devam ser mantidas por obrigação legal, prevenção de fraude, segurança, exercício regular de direitos ou outra hipótese legal.'],
['23. MENORES DE IDADE','O Bora Trampa deverá definir nos Termos de Uso a idade mínima. Havendo tratamento de dados de crianças ou adolescentes, serão observadas as exigências específicas da legislação e o melhor interesse desses titulares.'],
['24. ALTERAÇÕES','Esta Política poderá ser atualizada para refletir mudanças no aplicativo, legislação, tecnologia ou operações. Alterações relevantes poderão ser comunicadas pelos canais disponíveis.'],
['25. CONTATO','Bora Trampa\nRazão social: [RAZÃO SOCIAL]\nCNPJ: [CNPJ]\nE-mail: [E-MAIL]\nEndereço: [ENDEREÇO]\nEncarregado/DPO: [NOME/E-MAIL]'],
];

export default function PrivacyPage(){return <main className="legal-page"><header className="legal-nav"><Link href="/"><img src="/logo-bora-trampar.jpeg" alt="Bora Trampa" /></Link><Link href="/">← Voltar para a página inicial</Link></header><section className="legal-hero"><div className="eyebrow"><i/> Proteção de dados</div><h1>Política de <em>Privacidade.</em></h1><p>Como o Bora Trampa coleta, utiliza, armazena, compartilha e protege dados pessoais.</p><small>ÚLTIMA ATUALIZAÇÃO <b>[DATA]</b></small><label>Minuta para revisão jurídica</label></section><div className="legal-layout"><aside><span>nesta política</span>{sections.map(([title],i)=><a href={`#privacy-${i}`} key={title}>{title}</a>)}</aside><article><div className="welcome"><p>O Bora Trampa valoriza a privacidade e a proteção dos dados pessoais.</p><p>Esta Política explica as práticas aplicáveis ao uso da plataforma, em conformidade com a LGPD e demais normas aplicáveis.</p></div>{sections.map(([title,text],i)=><section id={`privacy-${i}`} key={title}><small>{String(i+1).padStart(2,'0')}</small><div><h2>{title}</h2><p className="preserve">{text}</p></div></section>)}<div className="lawyer-note"><b>Nota ao advogado</b><p>Esta é uma minuta inicial preparada com base no modelo informado para o Bora Trampa. Solicita-se revisão jurídica integral, especialmente quanto às bases legais, dados biométricos, documentos de profissionais, pagamentos, retenção e repasse, compartilhamento com terceiros, transferência internacional, direitos dos titulares, responsabilidade da plataforma e adequação ao CDC e demais normas aplicáveis.</p></div></article></div><footer className="legal-footer"><Link href="/"><img src="/logo-bora-trampar.jpeg" alt="Bora Trampa" /></Link><Link href="/termos-uso">Termos de Uso ↗</Link></footer></main>}
