import Link from 'next/link';

const sections: [string, string][] = [
['1. O QUE É O BORA TRAMPA','O Bora Trampa é uma plataforma tecnológica destinada a conectar clientes que procuram serviços a profissionais que oferecem serviços. A plataforma poderá permitir que o cliente encontre profissionais, consulte informações, solicite serviços, realize pagamentos, acompanhe contratações e avalie serviços. O Bora Trampa atua como plataforma de intermediação e tecnologia, não sendo, salvo quando expressamente informado, empregador dos profissionais cadastrados.'],
['2. ACEITAÇÃO DOS TERMOS','Para utilizar determinadas funcionalidades, o usuário deverá criar uma conta e fornecer as informações solicitadas. Ao marcar “Li e aceito os Termos de Uso”, declara que concorda com este documento. A Política de Privacidade possui regras próprias e deverá ser consultada separadamente.'],
['3. CADASTRO DO USUÁRIO','O usuário deverá fornecer informações verdadeiras, completas e atualizadas. Cada pessoa deverá utilizar sua própria conta e é responsável pela segurança de suas credenciais. Informações falsas, fraudulentas ou utilização indevida poderão resultar em restrição, suspensão ou encerramento do acesso, observada a legislação aplicável.'],
['4. CADASTRO DO PROFISSIONAL','O profissional poderá cadastrar os serviços que está apto a oferecer e é responsável pela veracidade das informações apresentadas em seu perfil, incluindo nome, foto, descrição, categorias, experiência, local, preços, disponibilidade e documentos solicitados. Deverá possuir capacidade e qualificação necessárias para executar os serviços.'],
['5. RELAÇÃO ENTRE CLIENTE E PROFISSIONAL','A contratação estabelece uma relação entre o cliente e o profissional responsável. O profissional é responsável pela execução adequada e o cliente por fornecer informações corretas e cumprir as condições acordadas. O Bora Trampa disponibiliza a tecnologia para facilitar essa conexão.'],
['6. SOLICITAÇÃO E CONTRATAÇÃO','O cliente poderá pesquisar profissionais e serviços. Antes da contratação, poderão ser apresentadas informações como serviço, profissional, data, horário, local, valor, taxas e condições de cancelamento. A contratação será confirmada conforme o fluxo do aplicativo.'],
['7. PAGAMENTOS','Poderão ser utilizados meios de pagamento da plataforma ou de parceiros. O valor poderá incluir serviço, taxa de intermediação e outras taxas informadas previamente. As condições serão apresentadas antes da confirmação e poderão ser utilizados processadores especializados.'],
['8. CANCELAMENTOS, REEMBOLSOS E ESTORNOS','As condições poderão variar conforme o serviço. Quando aplicável, o aplicativo informará previamente condições e taxas. Pedidos de reembolso ou estorno serão analisados conforme a contratação, estes Termos e a legislação aplicável.'],
['9. RESPONSABILIDADES DO CLIENTE','O cliente deverá fornecer informações verdadeiras; respeitar os profissionais; fornecer condições adequadas; cumprir pagamentos; não utilizar a plataforma para atividades ilícitas, ameaças, assédio, discriminação, violência, fraudes ou golpes.'],
['10. RESPONSABILIDADES DO PROFISSIONAL','O profissional deverá fornecer informações verdadeiras; prestar o serviço contratado; cumprir horários; manter comportamento profissional; respeitar clientes; não praticar ameaças, assédio, discriminação ou violência; não utilizar a plataforma para atividades ilícitas; e cumprir suas obrigações legais.'],
['11. CONDUTAS PROIBIDAS','É proibido utilizar o Bora Trampa para fraudes, atividades ilegais, falsificação, contas falsas ou de terceiros, invasão, vírus, conteúdo ilegal ou ofensivo, assédio, ameaças, violência, discriminação ou qualquer finalidade que viole a legislação brasileira. A conta poderá ser suspensa ou encerrada.'],
['12. AVALIAÇÕES','As avaliações deverão ser verdadeiras e relacionadas à experiência ocorrida. Não serão permitidas avaliações falsas, ofensivas, discriminatórias ou ameaçadoras. O Bora Trampa poderá analisar e remover avaliações que violem estes Termos ou a legislação.'],
['13. COMUNICAÇÕES','O Bora Trampa poderá enviar comunicações sobre contratações, serviços, pagamentos, cancelamentos, segurança, atualizações e suporte. Comunicações promocionais seguirão as regras aplicáveis e poderão possuir opção de cancelamento.'],
['14. CONTEÚDO PUBLICADO PELO USUÁRIO','O usuário poderá inserir informações, fotos, descrições e avaliações, declarando possuir os direitos necessários e não devendo publicar material que viole direitos de terceiros ou a legislação. Conteúdos irregulares poderão ser removidos.'],
['15. PROPRIEDADE INTELECTUAL','O aplicativo, site, nome, logotipos, identidade visual, textos, sistemas, códigos e funcionalidades são protegidos pela legislação. Não poderão ser copiados, modificados, reproduzidos, vendidos, distribuídos ou explorados comercialmente sem autorização.'],
['16. DISPONIBILIDADE DA PLATAFORMA','O Bora Trampa buscará manter a plataforma disponível, mas poderão ocorrer interrupções por manutenção, atualizações, falhas técnicas, fornecedores, serviços terceiros ou eventos fora do controle razoável. Não há garantia de disponibilidade ininterrupta.'],
['17. RESPONSABILIDADE SOBRE OS SERVIÇOS','O profissional é responsável pela execução do serviço. O Bora Trampa fornece ferramentas tecnológicas para facilitar a conexão, sem eliminar direitos do consumidor quando aplicáveis. Reclamações poderão ser encaminhadas pelos canais de atendimento.'],
['18. SEGURANÇA','O Bora Trampa poderá adotar medidas técnicas e administrativas para proteger a plataforma e as informações dos usuários. O usuário deverá colaborar mantendo credenciais protegidas e comunicando atividades suspeitas.'],
['19. PRIVACIDADE E PROTEÇÃO DE DADOS','O tratamento de dados pessoais será explicado na Política de Privacidade, que deverá informar dados coletados, finalidades, compartilhamentos, armazenamento e direitos dos titulares.'],
['20. SUSPENSÃO OU ENCERRAMENTO DA CONTA','A conta poderá ser suspensa ou encerrada por violação destes Termos, fraude, uso ilegal, risco à segurança, informações falsas, comportamento abusivo ou descumprimento de obrigações. Quando aplicável, o usuário poderá contatar o suporte.'],
['21. ALTERAÇÕES DESTES TERMOS','O Bora Trampa poderá atualizar os Termos para refletir alterações na plataforma, legislação ou serviços. Alterações relevantes poderão ser comunicadas por canais apropriados e a versão atualizada ficará disponível.'],
['22. ATENDIMENTO E SUPORTE','O usuário poderá entrar em contato pelos canais oficiais disponibilizados no aplicativo ou site. As solicitações serão analisadas conforme sua natureza e os prazos aplicáveis.'],
['23. LEGISLAÇÃO APLICÁVEL','Estes Termos serão interpretados de acordo com as leis da República Federativa do Brasil. Relações de consumo observarão também a legislação de proteção ao consumidor aplicável.'],
['24. DISPOSIÇÕES FINAIS','Caso alguma disposição seja considerada inválida ou inexigível, as demais permanecerão válidas. A utilização da plataforma representa a concordância do usuário com estes Termos, respeitadas as disposições legais aplicáveis.'],
];

export default function TermsPage(){return <main className="legal-page"><header className="legal-nav"><Link href="/"><img src="/logo-bora-trampar-crop.png" alt="Bora Trampa" /></Link><Link href="/">← Voltar para a página inicial</Link></header><section className="legal-hero"><div className="eyebrow"><i/> Documento oficial</div><h1>Termos de <em>Uso.</em></h1><p>As regras para utilização do aplicativo, site e demais serviços oferecidos pelo Bora Trampa.</p><small>ÚLTIMA ATUALIZAÇÃO <b>03/09/2026</b></small></section><div className="legal-layout"><aside><span>neste documento</span>{sections.map(([title],i)=><a href={`#term-${i}`} key={title}>{title}</a>)}</aside><article><div className="welcome"><p>Bem-vindo ao Bora Trampa.</p><p>Estes Termos de Uso estabelecem as regras para utilização do aplicativo, site e demais serviços oferecidos pelo Bora Trampa.</p><p>Ao criar uma conta ou utilizar a plataforma, o usuário declara que leu, compreendeu e concorda com estes Termos de Uso.</p></div>{sections.map(([title,text],i)=><section id={`term-${i}`} key={title}><small>{String(i+1).padStart(2,'0')}</small><div><h2>{title}</h2><p>{text}</p></div></section>)}<div className="legal-end">BT · Fim do documento</div></article></div><footer className="legal-footer"><Link href="/"><img src="/logo-bora-trampar-crop.png" alt="Bora Trampa" /></Link><Link href="/politica-privacidade">Política de Privacidade ↗</Link></footer></main>}
