import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

interface TermSection {
  title: string;
  paragraphs?: string[];
  bullets?: string[];
}

@Component({
  selector: 'app-terms',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './terms.html',
  styleUrl: './terms.css'
})
export class Terms {
  readonly sections: TermSection[] = [
    { title: '1. O QUE É O BORA TRAMPA', paragraphs: ['O Bora Trampa é uma plataforma tecnológica destinada a conectar clientes que procuram serviços a profissionais que oferecem serviços.', 'A plataforma poderá permitir que o cliente encontre profissionais, consulte informações, solicite serviços, realize pagamentos, acompanhe contratações e avalie serviços.', 'O profissional poderá criar um perfil, divulgar seus serviços, receber solicitações de clientes e utilizar as ferramentas disponibilizadas pela plataforma.', 'O Bora Trampa atua como plataforma de intermediação e tecnologia, não sendo, salvo quando expressamente informado, empregador dos profissionais cadastrados.'] },
    { title: '2. ACEITAÇÃO DOS TERMOS', paragraphs: ['Para utilizar determinadas funcionalidades do Bora Trampa, o usuário deverá criar uma conta e fornecer as informações solicitadas.', 'Ao marcar a opção “Li e aceito os Termos de Uso”, o usuário declara que concorda com as regras deste documento.', 'A Política de Privacidade possui regras próprias e deverá ser consultada separadamente.'] },
    { title: '3. CADASTRO DO USUÁRIO', paragraphs: ['O usuário deverá fornecer informações verdadeiras, completas e atualizadas.', 'Cada pessoa deverá utilizar sua própria conta e não poderá fornecer sua senha ou permitir que terceiros utilizem sua conta.', 'O usuário é responsável pela segurança de suas credenciais de acesso.', 'Caso sejam identificadas informações falsas, fraudulentas ou utilização indevida da conta, o Bora Trampa poderá restringir, suspender ou encerrar o acesso à plataforma, observada a legislação aplicável.'] },
    { title: '4. CADASTRO DO PROFISSIONAL', paragraphs: ['O profissional poderá cadastrar os serviços que está apto a oferecer.', 'O profissional é responsável pela veracidade das informações apresentadas em seu perfil, incluindo, quando aplicável: nome; foto; descrição dos serviços; categorias; experiência; local de atendimento; preços; disponibilidade; e documentos ou informações solicitadas pela plataforma.', 'O profissional deverá possuir capacidade e qualificação necessárias para executar os serviços que oferecer.', 'O Bora Trampa poderá estabelecer procedimentos de verificação de identidade, informações profissionais ou outros requisitos de segurança.'] },
    { title: '5. RELAÇÃO ENTRE CLIENTE E PROFISSIONAL', paragraphs: ['A contratação de um serviço realizada por meio do Bora Trampa estabelece uma relação entre o cliente e o profissional responsável pela prestação do serviço.', 'O profissional é responsável pela execução adequada do serviço contratado.', 'O cliente é responsável por fornecer informações corretas sobre o serviço solicitado e pelo cumprimento das condições acordadas.', 'O Bora Trampa disponibiliza a tecnologia para facilitar essa conexão, não assumindo automaticamente a posição de prestador do serviço.'] },
    { title: '6. SOLICITAÇÃO E CONTRATAÇÃO', paragraphs: ['O cliente poderá pesquisar profissionais e serviços disponíveis na plataforma.', 'Antes da contratação, poderão ser apresentadas informações como: serviço; profissional; data e horário; local; valor; taxas aplicáveis; condições de cancelamento; e outras informações relevantes.', 'A contratação será considerada confirmada de acordo com o fluxo disponibilizado pelo aplicativo.'] },
    { title: '7. PAGAMENTOS', paragraphs: ['Quando o pagamento for realizado por meio do Bora Trampa, poderão ser utilizados os meios de pagamento disponibilizados pela plataforma ou por seus parceiros.', 'O valor apresentado ao cliente poderá incluir: valor do serviço; taxa de intermediação; e outras taxas eventualmente aplicáveis, quando informadas previamente.', 'As condições de pagamento serão apresentadas ao usuário antes da confirmação da contratação.', 'O Bora Trampa poderá utilizar empresas especializadas em processamento de pagamentos.'] },
    { title: '8. CANCELAMENTOS, REEMBOLSOS E ESTORNOS', paragraphs: ['As condições de cancelamento poderão variar conforme o serviço contratado.', 'Quando aplicável, o aplicativo informará previamente ao cliente as condições e eventuais taxas relacionadas ao cancelamento.', 'Pedidos de reembolso ou estorno serão analisados de acordo com as condições da contratação, estes Termos de Uso e a legislação aplicável.'] },
    { title: '9. RESPONSABILIDADES DO CLIENTE', paragraphs: ['O cliente deverá:'], bullets: ['Fornecer informações verdadeiras;', 'Respeitar os profissionais;', 'Fornecer condições adequadas para realização do serviço;', 'Cumprir os pagamentos devidos;', 'Não utilizar a plataforma para atividades ilícitas;', 'Não praticar ameaças, assédio, discriminação ou qualquer forma de violência;', 'Não utilizar a plataforma para fraudes ou golpes.'] },
    { title: '10. RESPONSABILIDADES DO PROFISSIONAL', paragraphs: ['O profissional deverá:'], bullets: ['Fornecer informações verdadeiras;', 'Prestar os serviços de acordo com o que foi contratado;', 'Cumprir horários e condições acordadas;', 'Manter comportamento profissional;', 'Respeitar os clientes;', 'Não praticar ameaças, assédio, discriminação ou qualquer forma de violência;', 'Não utilizar a plataforma para atividades ilícitas;', 'Cumprir as obrigações legais relacionadas à sua atividade profissional.'] },
    { title: '11. CONDUTAS PROIBIDAS', paragraphs: ['É proibido utilizar o Bora Trampa para: fraudes ou golpes; atividades ilegais; falsificação de informações; criação de contas falsas; utilização de contas de terceiros; tentativas de invasão ou comprometimento da plataforma; distribuição de vírus ou códigos maliciosos; publicação de conteúdo ilegal ou ofensivo; assédio, ameaças ou violência; práticas discriminatórias; ou qualquer finalidade que viole a legislação brasileira.', 'O usuário que violar estas regras poderá ter sua conta suspensa ou encerrada.'] },
    { title: '12. AVALIAÇÕES', paragraphs: ['Após a realização de um serviço, clientes e profissionais poderão ter acesso a mecanismos de avaliação, quando disponibilizados pelo Bora Trampa.', 'As avaliações deverão ser verdadeiras e relacionadas à experiência efetivamente ocorrida.', 'Não serão permitidas avaliações falsas, ofensivas, discriminatórias, ameaçadoras ou utilizadas para prejudicar injustamente outro usuário.', 'O Bora Trampa poderá analisar e remover avaliações que violem estes Termos de Uso ou a legislação aplicável.'] },
    { title: '13. COMUNICAÇÕES', paragraphs: ['O Bora Trampa poderá enviar comunicações relacionadas à utilização da plataforma, incluindo confirmações de contratação, informações sobre serviços, pagamentos, cancelamentos, segurança da conta, atualizações importantes e suporte.', 'Comunicações promocionais seguirão as regras aplicáveis e, quando necessário, poderão possuir opção de cancelamento.'] },
    { title: '14. CONTEÚDO PUBLICADO PELO USUÁRIO', paragraphs: ['O usuário poderá inserir informações, fotos, descrições, avaliações e outros conteúdos na plataforma.', 'O usuário declara possuir os direitos necessários para publicar esse conteúdo e não deverá publicar material que viole direitos de terceiros ou a legislação.', 'O Bora Trampa poderá remover conteúdos que violem estes Termos de Uso.'] },
    { title: '15. PROPRIEDADE INTELECTUAL', paragraphs: ['O aplicativo, site, nome Bora Trampa, logotipos, identidade visual, textos, sistemas, códigos, funcionalidades e demais elementos pertencentes à plataforma são protegidos pela legislação aplicável.', 'O usuário não poderá copiar, modificar, reproduzir, vender, distribuir ou explorar comercialmente esses elementos sem autorização.'] },
    { title: '16. DISPONIBILIDADE DA PLATAFORMA', paragraphs: ['O Bora Trampa buscará manter a plataforma disponível e funcionando adequadamente.', 'Entretanto, poderão ocorrer interrupções temporárias decorrentes de manutenção, atualizações, falhas técnicas, problemas de internet, falhas de fornecedores ou serviços terceiros, ou eventos fora do controle razoável da plataforma.', 'O Bora Trampa não garante disponibilidade ininterrupta do aplicativo.'] },
    { title: '17. RESPONSABILIDADE SOBRE OS SERVIÇOS', paragraphs: ['O profissional é responsável pela execução do serviço que oferece.', 'O Bora Trampa disponibiliza ferramentas tecnológicas para facilitar a conexão entre clientes e profissionais.', 'Isso não elimina os direitos do consumidor previstos na legislação aplicável, quando esta for aplicável à relação.', 'Eventuais reclamações relacionadas à prestação do serviço poderão ser encaminhadas pelos canais de atendimento disponibilizados pelo Bora Trampa.'] },
    { title: '18. SEGURANÇA', paragraphs: ['O Bora Trampa poderá adotar medidas técnicas e administrativas destinadas a proteger a plataforma e as informações dos usuários.', 'O usuário também deverá colaborar com a segurança da plataforma, mantendo suas credenciais protegidas e comunicando atividades suspeitas.'] },
    { title: '19. PRIVACIDADE E PROTEÇÃO DE DADOS', paragraphs: ['O tratamento de dados pessoais realizado pelo Bora Trampa será explicado na Política de Privacidade da plataforma.', 'A Política de Privacidade deverá informar, entre outros aspectos, quais dados são coletados, as finalidades do tratamento, compartilhamentos, armazenamento e direitos dos titulares.'] },
    { title: '20. SUSPENSÃO OU ENCERRAMENTO DA CONTA', paragraphs: ['O Bora Trampa poderá suspender ou encerrar uma conta quando houver indícios ou confirmação de violação destes Termos; fraude; uso ilegal da plataforma; risco à segurança de usuários; informações falsas; comportamento abusivo; ou descumprimento de obrigações relacionadas à plataforma.', 'Sempre que aplicável, o usuário poderá entrar em contato com o suporte para obter informações sobre a situação de sua conta.'] },
    { title: '21. ALTERAÇÕES DESTES TERMOS', paragraphs: ['O Bora Trampa poderá atualizar estes Termos de Uso para refletir alterações na plataforma, na legislação ou nos serviços oferecidos.', 'Quando houver alterações relevantes, o usuário poderá ser informado por meio do aplicativo ou de outros canais apropriados.', 'A versão atualizada ficará disponível na plataforma.'] },
    { title: '22. ATENDIMENTO E SUPORTE', paragraphs: ['O usuário poderá entrar em contato com o Bora Trampa pelos canais oficiais disponibilizados no aplicativo ou no site.', 'As solicitações serão analisadas conforme sua natureza e os prazos aplicáveis.'] },
    { title: '23. LEGISLAÇÃO APLICÁVEL', paragraphs: ['Estes Termos de Uso serão interpretados de acordo com as leis da República Federativa do Brasil.', 'As relações de consumo, quando existentes, observarão também a legislação de proteção ao consumidor aplicável.'] },
    { title: '24. DISPOSIÇÕES FINAIS', paragraphs: ['Caso alguma disposição destes Termos seja considerada inválida ou inexigível, as demais disposições permanecerão válidas na medida permitida pela legislação.', 'A utilização da plataforma representa a concordância do usuário com estes Termos de Uso, respeitadas as disposições legais aplicáveis.'] }
  ];
}
